version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
  pre_build:
    commands:
      - echo "Pre-build phase started on `date`"
      - echo "Listing files in source directory..."
      - ls -la
  build:
    commands:
      - echo "Build phase started on `date`"
      - echo "No compilation needed for static HTML"
      - echo "Files ready for deployment"
  post_build:
    commands:
      - echo "Post-build phase started on `date`"
      - echo "Build completed successfully"

artifacts:
  files:
    - '**/*'
  name: BuildArtifact
